package edu.uark.registerapp.commands.employees;

import java.util.UUID;

import javax.transaction.Transactional;

import org.apache.commons.lang3.StringUtils;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import edu.uark.registerapp.commands.ResultCommandInterface;
import edu.uark.registerapp.commands.exceptions.ConflictException;
import edu.uark.registerapp.commands.exceptions.NotFoundException;
import edu.uark.registerapp.commands.exceptions.UnprocessableEntityException;
import edu.uark.registerapp.models.api.Employee;
import edu.uark.registerapp.models.entities.EmployeeEntity;
import edu.uark.registerapp.models.repositories.EmployeeRepository;
import net.bytebuddy.dynamic.DynamicType.Builder.FieldDefinition.Optional;


 //(JK)
@Service
public class EmployeeCreateCommand implements ResultCommandInterface<Employee> {

    @Override
	public Employee execute() {
		this.validateProperties();

        this.checkInitial();

		final EmployeeEntity createdEmployeeEntity = this.createEmployeeEntity();

		// Synchronize information generated by the database upon INSERT.
		this.apiEmployee.setId(createdEmployeeEntity.getId()); 
		this.apiEmployee.setCreatedOn(createdEmployeeEntity.getCreatedOn());

		return this.apiEmployee;
	}

	// Helper methods
	private void validateProperties() {
		if (StringUtils.isBlank(this.apiEmployee.getEmployeeId())) {
			throw new UnprocessableEntityException("Id");
        }
        if (StringUtils.isBlank(this.apiEmployee.getFirstName())){
            throw new UnprocessableEntityException("First Name");
        }
        if (StringUtils.isBlank(this.apiEmployee.getLastName())){
            throw new UnprocessableEntityException("Last Name");
        }
        if (StringUtils.isBlank(this.apiEmployee.getPassword())){
            throw new UnprocessableEntityException("Password");
        }  
    }
    
    private void checkInitial(){
        if(this.apiEmployee.getIsInitialEmployee()){
            this.apiEmployee.setClassification(1);
        }
    }
    

	@Transactional
	private EmployeeEntity createEmployeeEntity() {
		final java.util.Optional<EmployeeEntity> queriedEmployeeEntity =
			this.employeeRepository
				.findById(this.apiEmployee.getId());

		if (queriedEmployeeEntity.isPresent()) {
			// Lookupcode already defined for another product.
			throw new ConflictException("Id");
		}

		// No ENTITY object was returned from the database, thus the API object's
		// lookupcode must be unique.

		// Write, via an INSERT, the new record to the database.
		return this.employeeRepository.save(
			new EmployeeEntity(apiEmployee));
	}

	// Properties (JK)
	private Employee apiEmployee;
	public Employee getApiEmployee() {
		return this.apiEmployee;
	}
	public EmployeeCreateCommand setApiEmployee(final Employee apiEmployee) {
		this.apiEmployee = apiEmployee;
		return this;
	}

	@Autowired
	private EmployeeRepository employeeRepository;
}